### ISSUE TITLE
A good candidate for core?

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/editorimgdimensionsync#1]
Just saw this for the first time. This seems like it would be a good candidate for core. It's annoying to have to set the dimensions. I usually delete the height and only set the width, but this is easier.

Is there a core issue for this already?

**Comment by herbdool** [comment]
This is kinda related https://github.com/backdrop/backdrop-issues/issues/3599

**Comment by herbdool** [comment]
I created a core issue https://github.com/backdrop/backdrop-issues/issues/6385

**Comment by indigoxela** [comment]
Hehe, yes, ... this module here exists because of dissent in a core issue. Things like that can happen. :shrug: 

Trying to get that module into core will just start the same discussions again, which I'm not really fond of.
I'm happy with the functionality, just the way it is now.

**Comment by herbdool** [comment]
Ah, I didn't see that issue where that was discussed already. I get it.
